import { useEffect } from 'react';
import Head from 'next/head'
import { HomeSection } from '@/components/'

export default function Home() {
	return (
		<>
			<Head>
				<title>LUXICON</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/icon.svg" />
			</Head>
			<main className='w-full'>
				<HomeSection />
				<div className='w-full h-[100vh]'>section2</div>
				<div className='w-full h-[100vh]'>section3</div>
				<div className='w-full h-[100vh]'>section4</div>
			</main>
		</>
	)
}
